export const employeesList = [
  { "name": "Abiol, Tristan P." },
  { "name": "Bartolo, John Daniel A." },
  { "name": "Cervantes, Joseph S." },
  { "name": "Crisostomo, Emmanuel C." },
  { "name": "Cue, Karlo Antonio B." },
  { "name": "De Guzman, Krizza Mhei A." },
  { "name": "Guitierrez, Arnel S." },
  { "name": "Mendoza, Baby Angela R." },
  { "name": "Navarro, Frederick P." },
  { "name": "Nicolas, James Patrick S." },
  { "name": "Ochoa, Joseph Gary G." },
  { "name": "Owera, Mary Christian Joy C." },
  { "name": "Palad, Arthur L." },
  { "name": "Perez, Ronalyn C." },
  { "name": "Sacdalan, Bryan Allen S." },
  { "name": "Santiago, Christian Dave T." },
  { "name": "Santiago, Sandy I." },
  { "name": "Santos, Joe Allann S." },
  { "name": "Santos, Paul Andrew R." },
  { "name": "Tolentino, Gilbert T." },
  { "name": "Tolentino, Joseph C." },
  { "name": "Valerio, Rhea Liza R." },
  { "name": "Manahan, Jose Fernando G." },
  { "name": "Constantino, Antonia V." }
];
